services:
  - type: web
    name: contact-app
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: MYSQLHOST
        sync: false
      - key: MYSQLPORT
        value: "3306"
      - key: MYSQLDATABASE
        value: contactdb
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
      - key: PORT
        value: "8080"

databases:
  - name: contact-db
    databaseName: contactdb
    region: singapore
    plan: free
    mysqlMajorVersion: "8"
