services:
  - type: web
    name: contact-app
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: MYSQLHOST
        sync: false
      - key: MYSQLPORT
        value: "4000"
      - key: MYSQLDATABASE
        value: "contact_ap"
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
      - key: PORT
        value: "8080"
