services:
  - type: web
    name: contact-app
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: HOST
        sync: false
      - key: PORT
        value: "4000"
      - key: DATABASE
        value: contact_ap
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false
      - key: PORT
        value: "8080"

databases:
  - name: contact-db
    databaseName: contact_ap
    region: singapore
    plan: free
    mysqlMajorVersion: "8"
