services:
  - type: web
    name: contact-app
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: MYSQLHOST
        value: "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
      - key: MYSQLPORT
        value: "4000"
      - key: MYSQLDATABASE
        value: "contact_ap"
      - key: MYSQLUSER
        value: "2FZxrsCJYJcDj9Z.root"
      - key: MYSQLPASSWORD
        sync: false
      - key: MYSQL_JDBC_PARAMS
        value: "useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true&sslMode=REQUIRED&enabledTLSProtocols=TLSv1.2"
